//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int idEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int TipoDocumentoId { get; set; }
        public string NumeroDocumento { get; set; }
        public string CorreoElectronico { get; set; }
        public int GeneroId { get; set; }
        public Nullable<int> edad { get; set; }
        public bool Estado { get; set; }
    
        public virtual Genero Genero { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
